// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMSMarica.Data;

#nullable disable

namespace SMSMarica.Data.Migrations
{
    [DbContext(typeof(SmsMaricaDbContext))]
    [Migration("20260424190216_AddVeiculoFabricanteCorTipo")]
    partial class AddVeiculoFabricanteCorTipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smsmarica")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMSMarica.Data.Entities.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("assento_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("RotaDiariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rota_diaria_id");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AssentoId");

                    b.HasIndex("SessaoId");

                    b.HasIndex("RotaDiariaId", "AssentoId")
                        .IsUnique();

                    b.ToTable("translado_alocacao", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Assento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("FileiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("fileira_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("FileiraId", "Numero")
                        .IsUnique();

                    b.ToTable("veiculo_assento", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId")
                        .IsUnique();

                    b.ToTable("avaliacao", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.EventoChegada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofence_id");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("RotaDiariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rota_diaria_id");

                    b.HasKey("Id");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("RotaDiariaId", "OcorridoEm");

                    b.ToTable("rastreamento_evento_chegada", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Fileira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuantidadeAssentos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_assentos");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId", "Ordem")
                        .IsUnique();

                    b.ToTable("veiculo_fileira", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("RaioMetros")
                        .HasColumnType("integer")
                        .HasColumnName("raio_metros");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "ReferenciaId");

                    b.ToTable("rastreamento_geofence", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cnh");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("motorista", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Alergias")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alergias");

                    b.Property<int?>("AlturaCm")
                        .HasColumnType("integer")
                        .HasColumnName("altura_cm");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cns")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cns");

                    b.PrimitiveCollection<List<string>>("Comorbidades")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("comorbidades");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.PrimitiveCollection<List<string>>("Deficiencias")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("deficiencias");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("integer")
                        .HasColumnName("escolaridade");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer")
                        .HasColumnName("estado_civil");

                    b.Property<int>("FatorRh")
                        .HasColumnType("integer")
                        .HasColumnName("fator_rh");

                    b.PrimitiveCollection<List<string>>("MedicamentosContinuos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("medicamentos_continuos");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nacionalidade");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("naturalidade");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeDaMae")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_da_mae");

                    b.Property<string>("NomeDoPai")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_do_pai");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Ocupacao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("ocupacao");

                    b.Property<decimal?>("PesoKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso_kg");

                    b.Property<string>("PlanoSaude")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("plano_saude");

                    b.Property<int>("RacaCor")
                        .HasColumnType("integer")
                        .HasColumnName("raca_cor");

                    b.Property<string>("ResponsavelLegal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsavel_legal");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<string>("TelefoneCelular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_celular");

                    b.Property<string>("TelefonePrincipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_principal");

                    b.Property<string>("TelefoneResidencial")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_residencial");

                    b.Property<int>("TipoSanguineo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_sanguineo");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("NomeCompleto");

                    b.ToTable("paciente", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Periodicidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("DiasSemanaMascara")
                        .HasColumnType("integer")
                        .HasColumnName("dias_semana_mascara");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_dias");

                    b.Property<int>("QuantidadeSessoes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_sessoes");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_id");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId")
                        .IsUnique();

                    b.ToTable("tratamento_periodicidade", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.PontoGps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId", "CapturadoEm");

                    b.ToTable("rastreamento_ponto_gps", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.RotaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_em");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("translado_rota_diaria", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.SessaoDeTratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("ConfirmadaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmada_por_usuario_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<TimeOnly?>("HoraChegadaResidencia")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_chegada_residencia");

                    b.Property<TimeOnly?>("HoraChegadaUnidade")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_chegada_unidade");

                    b.Property<TimeOnly?>("HoraPrevistaBusca")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_prevista_busca");

                    b.Property<TimeOnly?>("HoraPrevistaRetorno")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_prevista_retorno");

                    b.Property<TimeOnly?>("HoraSaidaResidencia")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_saida_residencia");

                    b.Property<TimeOnly?>("HoraSaidaUnidade")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_saida_unidade");

                    b.Property<string>("MotivoNaoRealizacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_nao_realizacao");

                    b.Property<Guid?>("MotoristaIdaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_ida_id");

                    b.Property<Guid?>("MotoristaVoltaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_volta_id");

                    b.Property<string>("NomeAcompanhante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_acompanhante");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("ParentescoAcompanhante")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("parentesco_acompanhante");

                    b.Property<DateTime?>("RealizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_em");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_id");

                    b.Property<Guid?>("VeiculoIdaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_ida_id");

                    b.Property<Guid?>("VeiculoVoltaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_volta_id");

                    b.HasKey("Id");

                    b.HasIndex("DataPrevista");

                    b.HasIndex("Status");

                    b.HasIndex("TratamentoId", "DataPrevista");

                    b.ToTable("sessao_de_tratamento", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.TipoTratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipo_tratamento", "smsmarica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0193d000-0000-7000-a000-000000000001"),
                            Ativo = true,
                            Codigo = "hemodialise",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Hemodiálise"
                        },
                        new
                        {
                            Id = new Guid("0193d000-0000-7000-a000-000000000002"),
                            Ativo = true,
                            Codigo = "radioterapia",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Radioterapia"
                        });
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Tratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoSusLiberacao")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_sus_liberacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrado_em");

                    b.Property<TimeOnly?>("HoraPrevistaBusca")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_prevista_busca");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid?>("TipoTratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_tratamento_id");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TipoTratamentoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("tratamento", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("unidade", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculo", "smsmarica");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Alocacao", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Assento", "Assento")
                        .WithMany()
                        .HasForeignKey("AssentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMarica.Data.Entities.RotaDiaria", "RotaDiaria")
                        .WithMany("Alocacoes")
                        .HasForeignKey("RotaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMSMarica.Data.Entities.SessaoDeTratamento", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assento");

                    b.Navigation("RotaDiaria");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Assento", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Fileira", "Fileira")
                        .WithMany("Assentos")
                        .HasForeignKey("FileiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fileira");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Avaliacao", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.SessaoDeTratamento", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.EventoChegada", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMarica.Data.Entities.RotaDiaria", "RotaDiaria")
                        .WithMany()
                        .HasForeignKey("RotaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geofence");

                    b.Navigation("RotaDiaria");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Fileira", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Veiculo", "Veiculo")
                        .WithMany("Fileiras")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Geofence", b =>
                {
                    b.OwnsOne("SMSMarica.Data.Entities.Gps", "Centro", b1 =>
                        {
                            b1.Property<Guid>("GeofenceId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centro_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centro_longitude");

                            b1.HasKey("GeofenceId");

                            b1.ToTable("rastreamento_geofence", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("GeofenceId");
                        });

                    b.Navigation("Centro")
                        .IsRequired();
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Paciente", b =>
                {
                    b.OwnsOne("SMSMarica.Data.Entities.ContatoEmergencia", "ContatoEmergencia", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("contato_emergencia_nome");

                            b1.Property<string>("Parentesco")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("contato_emergencia_parentesco");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("contato_emergencia_telefone");

                            b1.HasKey("PacienteId");

                            b1.ToTable("paciente", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("SMSMarica.Data.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("PontoReferencia")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_ponto_referencia");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("endereco_uf");

                            b1.HasKey("PacienteId");

                            b1.ToTable("paciente", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("SMSMarica.Data.Entities.Gps", "GpsResidencia", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("residencia_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("residencia_longitude");

                            b1.HasKey("PacienteId");

                            b1.ToTable("paciente", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("ContatoEmergencia");

                    b.Navigation("Endereco");

                    b.Navigation("GpsResidencia");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Periodicidade", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Tratamento", "Tratamento")
                        .WithOne("Periodicidade")
                        .HasForeignKey("SMSMarica.Data.Entities.Periodicidade", "TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.PontoGps", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SMSMarica.Data.Entities.Gps", "Coordenada", b1 =>
                        {
                            b1.Property<Guid>("PontoGpsId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("PontoGpsId");

                            b1.ToTable("rastreamento_ponto_gps", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PontoGpsId");
                        });

                    b.Navigation("Coordenada")
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.RotaDiaria", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMarica.Data.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.SessaoDeTratamento", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Tratamento", "Tratamento")
                        .WithMany("Sessoes")
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Tratamento", b =>
                {
                    b.HasOne("SMSMarica.Data.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMarica.Data.Entities.TipoTratamento", "TipoTratamento")
                        .WithMany()
                        .HasForeignKey("TipoTratamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMSMarica.Data.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("TipoTratamento");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Unidade", b =>
                {
                    b.OwnsOne("SMSMarica.Data.Entities.Gps", "Gps", b1 =>
                        {
                            b1.Property<Guid>("UnidadeId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("UnidadeId");

                            b1.ToTable("unidade", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("UnidadeId");
                        });

                    b.Navigation("Gps")
                        .IsRequired();
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Fileira", b =>
                {
                    b.Navigation("Assentos");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.RotaDiaria", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Tratamento", b =>
                {
                    b.Navigation("Periodicidade");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("SMSMarica.Data.Entities.Veiculo", b =>
                {
                    b.Navigation("Fileiras");
                });
#pragma warning restore 612, 618
        }
    }
}
