// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMSMais.Data;

#nullable disable

namespace SMSMais.Data.Migrations
{
    [DbContext(typeof(SmsMaisDbContext))]
    [Migration("20260423023824_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smsmarica")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMSMais.Data.Entities.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("assento_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("RotaDiariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rota_diaria_id");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AssentoId");

                    b.HasIndex("SessaoId");

                    b.HasIndex("RotaDiariaId", "AssentoId")
                        .IsUnique();

                    b.ToTable("translado_alocacao", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Assento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("FileiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("fileira_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("FileiraId", "Numero")
                        .IsUnique();

                    b.ToTable("veiculo_assento", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId")
                        .IsUnique();

                    b.ToTable("avaliacao", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.EventoChegada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofence_id");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("RotaDiariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rota_diaria_id");

                    b.HasKey("Id");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("RotaDiariaId", "OcorridoEm");

                    b.ToTable("rastreamento_evento_chegada", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Fileira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuantidadeAssentos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_assentos");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId", "Ordem")
                        .IsUnique();

                    b.ToTable("veiculo_fileira", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("RaioMetros")
                        .HasColumnType("integer")
                        .HasColumnName("raio_metros");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "ReferenciaId");

                    b.ToTable("rastreamento_geofence", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cnh");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("motorista", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cns")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cns");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("paciente", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Periodicidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("DiasSemanaMascara")
                        .HasColumnType("integer")
                        .HasColumnName("dias_semana_mascara");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_dias");

                    b.Property<int>("QuantidadeSessoes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_sessoes");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_id");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId")
                        .IsUnique();

                    b.ToTable("tratamento_periodicidade", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.PontoGps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId", "CapturadoEm");

                    b.ToTable("rastreamento_ponto_gps", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.RotaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_em");

                    b.Property<Guid>("MotoristaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("translado_rota_diaria", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.SessaoDeTranslado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_id");

                    b.HasKey("Id");

                    b.HasIndex("DataPrevista");

                    b.HasIndex("TratamentoId", "DataPrevista");

                    b.ToTable("translado_sessao", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Tratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrado_em");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("tratamento", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("unidade", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculo", "smsmarica");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Alocacao", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Assento", "Assento")
                        .WithMany()
                        .HasForeignKey("AssentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMais.Data.Entities.RotaDiaria", "RotaDiaria")
                        .WithMany("Alocacoes")
                        .HasForeignKey("RotaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMSMais.Data.Entities.SessaoDeTranslado", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assento");

                    b.Navigation("RotaDiaria");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Assento", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Fileira", "Fileira")
                        .WithMany("Assentos")
                        .HasForeignKey("FileiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fileira");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Avaliacao", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.SessaoDeTranslado", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.EventoChegada", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMais.Data.Entities.RotaDiaria", "RotaDiaria")
                        .WithMany()
                        .HasForeignKey("RotaDiariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geofence");

                    b.Navigation("RotaDiaria");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Fileira", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Veiculo", "Veiculo")
                        .WithMany("Fileiras")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Geofence", b =>
                {
                    b.OwnsOne("SMSMais.Data.Entities.Gps", "Centro", b1 =>
                        {
                            b1.Property<Guid>("GeofenceId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centro_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centro_longitude");

                            b1.HasKey("GeofenceId");

                            b1.ToTable("rastreamento_geofence", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("GeofenceId");
                        });

                    b.Navigation("Centro")
                        .IsRequired();
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Paciente", b =>
                {
                    b.OwnsOne("SMSMais.Data.Entities.Gps", "GpsResidencia", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("residencia_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("residencia_longitude");

                            b1.HasKey("PacienteId");

                            b1.ToTable("paciente", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("GpsResidencia")
                        .IsRequired();
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Periodicidade", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Tratamento", "Tratamento")
                        .WithOne("Periodicidade")
                        .HasForeignKey("SMSMais.Data.Entities.Periodicidade", "TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.PontoGps", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SMSMais.Data.Entities.Gps", "Coordenada", b1 =>
                        {
                            b1.Property<Guid>("PontoGpsId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("PontoGpsId");

                            b1.ToTable("rastreamento_ponto_gps", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("PontoGpsId");
                        });

                    b.Navigation("Coordenada")
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.RotaDiaria", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMais.Data.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.SessaoDeTranslado", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Tratamento", "Tratamento")
                        .WithMany("Sessoes")
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Tratamento", b =>
                {
                    b.HasOne("SMSMais.Data.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMSMais.Data.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Unidade", b =>
                {
                    b.OwnsOne("SMSMais.Data.Entities.Gps", "Gps", b1 =>
                        {
                            b1.Property<Guid>("UnidadeId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("UnidadeId");

                            b1.ToTable("unidade", "smsmarica");

                            b1.WithOwner()
                                .HasForeignKey("UnidadeId");
                        });

                    b.Navigation("Gps")
                        .IsRequired();
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Fileira", b =>
                {
                    b.Navigation("Assentos");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.RotaDiaria", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Tratamento", b =>
                {
                    b.Navigation("Periodicidade");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("SMSMais.Data.Entities.Veiculo", b =>
                {
                    b.Navigation("Fileiras");
                });
#pragma warning restore 612, 618
        }
    }
}
