// <auto-generated />
using System;
using Automais.Pabx.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automais.Pabx.Api.Migrations
{
    [DbContext(typeof(PabxDbContext))]
    [Migration("20260708141632_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.ArquivoGerenciado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RamalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Caminho")
                        .IsUnique();

                    b.HasIndex("RamalId");

                    b.ToTable("arquivo_gerenciado", (string)null);
                });

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.Ramal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mac")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("mac");

                    b.Property<string>("Marca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretCifrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Mac")
                        .IsUnique()
                        .HasFilter("mac IS NOT NULL");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("UnidadeId");

                    b.ToTable("ramal", (string)null);
                });

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayMk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gestor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TunnelIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("unidade", (string)null);
                });

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.ArquivoGerenciado", b =>
                {
                    b.HasOne("Automais.Pabx.Api.Data.Entities.Ramal", "Ramal")
                        .WithMany()
                        .HasForeignKey("RamalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ramal");
                });

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.Ramal", b =>
                {
                    b.HasOne("Automais.Pabx.Api.Data.Entities.Unidade", "Unidade")
                        .WithMany("Ramais")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Automais.Pabx.Api.Data.Entities.Unidade", b =>
                {
                    b.Navigation("Ramais");
                });
#pragma warning restore 612, 618
        }
    }
}
