// <auto-generated />
using System;
using Automais.Fhir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automais.Fhir.Data.Migrations
{
    [DbContext(typeof(FhirDbContext))]
    [Migration("20260804143431_AddPatientIdentifierGin")]
    partial class AddPatientIdentifierGin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fhir")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automais.Fhir.Data.Entities.ConditionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .HasFilter("encounter_id IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("condition", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.DocumentReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .HasFilter("encounter_id IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("document_reference", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.EncounterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classe")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("classe");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset?>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("PeriodEnd")
                        .HasFilter("period_end IS NOT NULL");

                    b.HasIndex("PeriodStart");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("encounter", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.LocationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PartOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_of_id");

                    b.Property<string>("PhysicalType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("physical_type");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PartOfId")
                        .HasFilter("part_of_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("location", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.MedicationAdministrationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("Effective")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Medicamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("medicamento");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .HasFilter("encounter_id IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.ToTable("medication_administration", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.MedicationRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AuthoredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authored_on");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Medicamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("medicamento");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .HasFilter("encounter_id IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("medication_request", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.ObservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("Effective")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("EncounterId")
                        .HasFilter("encounter_id IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PatientId")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("observation", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.OrganizationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Cnes")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnes");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("IdentifierSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_system");

                    b.Property<string>("IdentifierValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier_value");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PartOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_of_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("Cnes")
                        .HasFilter("cnes IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("PartOfId")
                        .HasFilter("part_of_id IS NOT NULL");

                    b.HasIndex("IdentifierSystem", "IdentifierValue")
                        .IsUnique()
                        .HasFilter("identifier_system IS NOT NULL AND NOT is_deleted");

                    b.ToTable("organization", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.PatientRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cns")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cns");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<DateOnly?>("Nascimento")
                        .HasColumnType("date")
                        .HasColumnName("nascimento");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("telefone");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("Cns")
                        .HasFilter("cns IS NOT NULL");

                    b.HasIndex("Cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("Nome");

                    b.HasIndex("Telefone");

                    b.ToTable("patient", "fhir");
                });

            modelBuilder.Entity("Automais.Fhir.Data.Entities.PractitionerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conselho")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("conselho");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MetaSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_source");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<string>("Registro")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("Conselho")
                        .HasFilter("conselho IS NOT NULL");

                    b.HasIndex("Cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("MetaSource");

                    b.HasIndex("Nome");

                    b.HasIndex("Registro")
                        .HasFilter("registro IS NOT NULL");

                    b.ToTable("practitioner", "fhir");
                });
#pragma warning restore 612, 618
        }
    }
}
