// <auto-generated />
using System;
using Automais.Zap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automais.Zap.Data.Migrations
{
    [DbContext(typeof(ZapDbContext))]
    [Migration("20260920144511_ArteDoTemplate")]
    partial class ArteDoTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("zap")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automais.Zap.Data.Entities.ConfiguracaoMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("app_id");

                    b.Property<string>("AppSecretCifrado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("app_secret_cifrado");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("base_url");

                    b.Property<string>("TokenSistemaCifrado")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("token_sistema_cifrado");

                    b.Property<string>("VerifyTokenCifrado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("verify_token_cifrado");

                    b.HasKey("Id");

                    b.ToTable("configuracao_meta", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.EntregaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DuracaoMs")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_ms");

                    b.Property<string>("Erro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erro");

                    b.Property<string>("PhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone_number_id");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("integer")
                        .HasColumnName("status_http");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("RecebidoEm")
                        .HasDatabaseName("ix_entrega_log_recebido_em");

                    b.HasIndex("TenantId", "RecebidoEm")
                        .HasDatabaseName("ix_entrega_log_tenant_recebido");

                    b.ToTable("entrega_log", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Midia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Altura")
                        .HasColumnType("integer")
                        .HasColumnName("altura");

                    b.Property<string>("Categoria")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("categoria");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<int?>("Largura")
                        .HasColumnType("integer")
                        .HasColumnName("largura");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "HashSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_midia_tenant_hash");

                    b.ToTable("midia", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Numero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DisplayPhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_phone_number");

                    b.Property<string>("PhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("phone_number_id");

                    b.Property<string>("Rotulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rotulo");

                    b.Property<string>("UrlDestinoOverride")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_destino_override");

                    b.Property<Guid>("WabaId")
                        .HasColumnType("uuid")
                        .HasColumnName("waba_id");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberId")
                        .IsUnique()
                        .HasDatabaseName("ux_numero_phone_number_id");

                    b.HasIndex("WabaId");

                    b.ToTable("numero", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TemplateArte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("AtualizadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por_usuario_id");

                    b.Property<Guid>("MidiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("midia_id");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("template");

                    b.Property<Guid>("WabaId")
                        .HasColumnType("uuid")
                        .HasColumnName("waba_id");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("WabaId", "Template")
                        .IsUnique()
                        .HasDatabaseName("ux_template_arte_waba_template");

                    b.ToTable("template_arte", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<DateTimeOffset?>("SuspensoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspenso_em");

                    b.Property<string>("SuspensoMotivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("suspenso_motivo");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_nome");

                    b.ToTable("tenant", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TenantToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefixo");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TodosNumeros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("todos_numeros");

                    b.Property<DateTimeOffset?>("UltimoUsoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_em");

                    b.HasKey("Id");

                    b.HasIndex("Prefixo")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_token_prefixo");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_token", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TenantTokenNumero", b =>
                {
                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<Guid>("NumeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("numero_id");

                    b.HasKey("TokenId", "NumeroId");

                    b.HasIndex("NumeroId");

                    b.ToTable("tenant_token_numero", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.UsuarioAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("Global")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("global");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_admin_email");

                    b.ToTable("usuario_admin", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.UsuarioTenant", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.HasKey("UsuarioId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("usuario_tenant", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Waba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<bool>("RoteamentoAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("roteamento_ativo");

                    b.Property<string>("SegredoEntregaCifrado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("segredo_entrega_cifrado");

                    b.Property<DateTimeOffset?>("SincronizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sincronizado_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UrlDestino")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_destino");

                    b.Property<string>("WabaId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("waba_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WabaId")
                        .IsUnique()
                        .HasDatabaseName("ux_waba_waba_id");

                    b.ToTable("waba", "zap");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Midia", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Numero", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Waba", "Waba")
                        .WithMany("Numeros")
                        .HasForeignKey("WabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waba");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TemplateArte", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Automais.Zap.Data.Entities.Waba", "Waba")
                        .WithMany()
                        .HasForeignKey("WabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Waba");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TenantToken", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TenantTokenNumero", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Numero", "Numero")
                        .WithMany()
                        .HasForeignKey("NumeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Automais.Zap.Data.Entities.TenantToken", "Token")
                        .WithMany("Numeros")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Numero");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.UsuarioTenant", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Tenant", "Tenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Automais.Zap.Data.Entities.UsuarioAdmin", "Usuario")
                        .WithMany("Tenants")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Waba", b =>
                {
                    b.HasOne("Automais.Zap.Data.Entities.Tenant", "Tenant")
                        .WithMany("Wabas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Usuarios");

                    b.Navigation("Wabas");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.TenantToken", b =>
                {
                    b.Navigation("Numeros");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.UsuarioAdmin", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Automais.Zap.Data.Entities.Waba", b =>
                {
                    b.Navigation("Numeros");
                });
#pragma warning restore 612, 618
        }
    }
}
